apiVersion: ENC[AES256_GCM,data:CzTA80OKvuC8D7S1WhXBSVqBbVzAh1eiuFY1,iv:Wm35V7/cX8xQGvc7diOxrupL+jU69wKb/hRTCOXnA2Q=,tag:Yn/dKPkmtFqmxuNUhQ1lpA==,type:str]
kind: ENC[AES256_GCM,data:dAJTa0myIeaSkA==,iv:bQcaeJakjtU/E/XT2b1qf5wZOx23yh//4VRx+Y2N5x0=,tag:3DWcnUbuQfEDwRe/BcBvDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4fENwYjZvnRV/Zzfk8sqwejv5TJW,iv:pFwq3kMh7rkOpGe5BZ1NNOIqKXPZFj4bFAvate7cQFc=,tag:Mdyv2GkPyba2bqgCbenibg==,type:str]
    namespace: ENC[AES256_GCM,data:4PYEdXHT,iv:IFJrgVA9+TB5xuvzVbBhAbnHFCtruDsmXewlLjEw/XM=,tag:SLE0GzGFykhv9pa7He88pA==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:PiqwQzXGXCKrhJ4EGRs4uw==,iv:/XTCG/zvtD05BoyULcbXrVlIYjwQQcBvykokXdnsI5o=,tag:eZ9hsPdu3ucEH4HTClE0WQ==,type:str]
          stringData:
            ANTHROPIC_API_KEY: ENC[AES256_GCM,data:YgSJ5sdRNJU1mI89dIRYQdSf0GLJ19B+60VKFLXQAR4vVZV+dQIsHbe1IDahILYhZySBzYn12JxO6hMWYV1FV3xaZf1+z7EpOKs53wbVCdDGDtpJ2caTcFamzVsfBOrNVGYsKUJmld4irSDc,iv:rsnnMCgzRXWZCeJ4riywWRYHd4JQMZZmS5hZG//FhjA=,tag:5VppbXiNvg37sC0JrmRU8g==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBra0t2emxhdXpydEtjRlpW
            NzRDZE1xNDJsZU5OMWVRdEFRSTJzT2k1WFhnCjJicGVJOGlVRGcvWlhUa2lDS2ND
            ZTdWOGZtdG1zSXNEM29kL05tRHQ1TlUKLS0tIHF6d2UrS1N0K0trM3E1Uis0YXRM
            UFNCUnFWTzBiOUhVWmVaSkcxTXVYMXcKJdJAV4yitDWQKaQvt+MhdnwJ+F462hiz
            W2JiLpxryHQRIq5WCVL532QIHB35qH9PBtUK6bMmQwpTVWbL+VSGtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T02:43:08Z"
    mac: ENC[AES256_GCM,data:gwVq3ALV7EQ3BtiXHO38ewx7CzcoUj3TlYnGmGSExtklf0L5oKonrBa9dGOed76b6oGkrZAHJ08FW/g2eVk35SWTrtPijnhM8WSbFCM3Clbv1u5NQqWXrpZrLO8lXJShIJiDZPOMky0lyPHDya/FPO49XHxfTjJ1foIIK8ovdyw=,iv:kEPYhO7Cmg/N1kOQj+MqvLPWgnzJK00OnGJaIeXnBZo=,tag:iYow6MgMbt8S+4D4e+7LtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
