apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: anthropic-credentials
    namespace: kagent
spec:
    secretTemplates:
        - name: kagent-anthropic
          stringData:
            ANTHROPIC_API_KEY: ENC[AES256_GCM,data:FSPh0ELwicBOV4MQxMC34cat0vJUxXh0QZo0NYd64MR4tSmP4NRYRHgd+0vOai9IMhF0mGaVUuYkqoGpVySGgunvV3m+uWJIse5f/kKGgfOP8ojRB1jaRftajY9yU0Kq7xvkgE3K5FZxynNg,iv:89f8oO9heCpRDvTTvy9GRJsEyZL/N5q7W5oeCMICs3s=,tag:Py52Qh9rkg3I0YPukwViUA==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK1FWalNBTk40UUQ0Z0Fy
            SFdLazVFN1hsSjRQb3NlMHk5Z1NmemMvbndZCkUyNldHZ1p2bjd1ZEhGdGVWcFdY
            Rk5MeHpTQ1pqeGtyYkNqYXpNZ3BoVncKLS0tIHdRYTN6S0cwenY5NWhqU01QdldN
            SzhLdGhBNDFMRk5yQldqQ25GSUw3MVEK06rqcTkeuGJCV0UQnLjw2BIiYupwCXa2
            9UpZbgYw33az7qSnDDNXnJpkFN5GRUaGIxGzSEFvyiV/sIKeBS79rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T03:44:28Z"
    mac: ENC[AES256_GCM,data:TWQihUzbmNj0ckVoLnHXlxLnSO/Jb3LiPORedrrV+H1LzLvgYhF4XNjPiR84GOO+i4Mtap21h+9goFFxQgvhv6bDlcPogVgSP8LFN9qDnX3P6vavvQoldwMy/xckZ1ZN2feVSHT93m2pSzhth2AAlnMVCywo0uus0bBamXXrmZ4=,iv:OTkuXtLnDrZpVIlJ+pc1n6a7TfSdZvdpuqskhsnctio=,tag:2qiw4DEdFRhMKlf4/NhkPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
