apiVersion: ENC[AES256_GCM,data:qkpcrs2+Z4oRumPFfLgzC0omlH93fQCUXNP4,iv:3Ojy3sDFzi2aCaXhVBWYLqpoo0wRgnUBLo6n5VbUzg0=,tag:WHo9hCcK3TrR+SM+izpMGw==,type:str]
kind: ENC[AES256_GCM,data:frzHG0mBV/h8AQ==,iv:K1c6onDp92UkcLjpubSMW2W0ulyFM4e5IGzw+wMZKkI=,tag:BJ7RIp8HaR+KG3bSgnfxLQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VTwzV9tYyyNAwDe4DhnWsq7V8rFmD2RJ,iv:xkHY2WqaU9tkpYESBKXLS57iCR/Du8CONwasZaaogx0=,tag:IlqP4KgAcZb/WCGGVquSQQ==,type:str]
    namespace: ENC[AES256_GCM,data:2tk8H9+sShx+,iv:wvjUMgGFh5uJpKZp+5cIL3qtx4eyQtJWeZiGX5V/hU0=,tag:VqOnGWCyxsZ2r8wviBx3gQ==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Hjr33mYEUK2MXGel34JLVP5r6A==,iv:MNteflYz437CgKwSLGixC5bu4Pss5I0iudnEkj6nEDc=,tag:xceOGhDbrmfKIrvGW7fuYw==,type:str]
          stringData:
            seaweedfs_s3_config: ENC[AES256_GCM,data:+uAYn2vlC5cXuxMaE7LarCa2CNBJMCpzXAFPnFUk7MIKzx2FD3sni6E/0liLY9WbvA3ocrip60PGTs9cvzQbt7AMLC/gf/QY5C2Auv6zkWyHO7tRCM8UUjQpu6gTz+ulthMkMsblkFTUhpTeJbf3GDKa8twjrhCuv76eVcvhNKRLFWr6gRfXUzAXKbeGBSQeiINtGD/n1VU71TaSURNe/H6Na+SwNQV+X4Qwmodl6W82FwQqemv+EBqJvINHZNPay/JVcixqSevLlEKMqZoSWdeK/wNqj+yP6Fr+YZ7h3nt6lKQzeFVtVlDm5UrGyotjy+G4PRShy4M4o3rwgBcrsrFgqhc/5u0ptwKGBjubj7ru/Ox6neNftV5DNb4EZ1YfMZQh,iv:qo7zPSJ1duOQ1DRQGhyxIemd7aODTXVM2RP/VNTkcRA=,tag:dN+Ib91EfBB8vDkWqOhZdg==,type:str]
        - name: ENC[AES256_GCM,data:53lFgBVLgJ0nczHwdOWqCvVd,iv:IDYEOWXyw3oCUaI7Ztg8NHcmZ0nKHRa4j4gKPvSF7OM=,tag:t8e3DXQKPIhhmbj8dGU06Q==,type:str]
          stringData:
            accessKey: ENC[AES256_GCM,data:XMf2roBZ/xQubtHiepmNRddCK6uipEgqphPDAMGyzQk=,iv:oGrieoKAB7nhoX255G1r4uzlMOVqdwszFyIixgPSxIg=,tag:oQ5TxzqR9jBjaCI+BZQEcw==,type:str]
            secretKey: ENC[AES256_GCM,data:mgRIkVmFEI0/VsaUS8V8YbTiHsWI0I7L+wTYr1l3beRPfo/DkypudQ==,iv:5DfO6torvpD9UUWldFalMQclkjCkYIyVtR/Qv6oUla0=,tag:0cm4Cfu8NiX1RAoaAKXSXA==,type:str]
        - name: ENC[AES256_GCM,data:FW7qraTzZGIsTM5rjoTJdYUx+Yj5aAXYs/W7YA==,iv:qn+DWrpo1EeZ1lq9D3agS9pF3sqmzTmuh+8mWohJC14=,tag:Q4BbgYjAFw0SYn4XR6SuhQ==,type:str]
          namespace: ENC[AES256_GCM,data:mr2e27TOcULP704ucg==,iv:HXioC5lHB+s5HsTJdjHcVvTaH9poJu5SIoO6vNQl5rc=,tag:uyB/NiCLqiQ2u4/2QxeIZg==,type:str]
          stringData:
            accessKey: ENC[AES256_GCM,data:b/Ngo0uFlKBKORzqf7bZKxGNcmFCP+K4wsmcISDoZAU=,iv:CV815RDgBsTS57jqKJoqjRjvdGOkXAJpSly1kr8K5hU=,tag:2dDCjhkPjZY0qxxDfu5Pbw==,type:str]
            secretKey: ENC[AES256_GCM,data:ADMR6NnEAI8MqxEaLqrThVwquc4he1GE8ZsVGCFdMZZvfrIVcs8vNA==,iv:UELyzXgNm0dbZ4gNwkZXN/dWeVTQUlYbSkkLsEVkyMk=,tag:J/L2GFvFbRgPTHkKux7VOQ==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRHBhS2dZM1hKZnIvR3VS
            NG4vQ1ZNcFBVUnkrL0UvQ0FqRlQ1OGNrU1hZCnJ2eUV6WGZWdzBXcVJQVHZHSSty
            NUdpMHBpUy8xYmRadU90L0tmeTE1UEEKLS0tIDR4N1ZZZzBZdWpaOTl3SS8xcDRa
            Umg5U3FQeVNrUzF3aFNDclFuZlB3Nm8KcqCS1EeDQW06KulSIbO89uvX8D6IgvZ0
            sdXi0CLmTnOyoclH1wdX7W9gexFApmGLVsZxVE6EQevEpk/GCBF9Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T02:17:18Z"
    mac: ENC[AES256_GCM,data:cgitOP+/c3t+p6cjEdr/6B6To9jNmtsmxNhSeNJXD+UGxb5AWwwrUNv7/pebo0CszZmGa6IbapNaxB5FyiaXLnR1YK+UthLOep73n4n0F7ym3nQriwsmiKvmREdTzHh0cu7C8gjbC73P1JzTK+zZGHHbL2sHJx3vLpLCe+GOUww=,iv:1BDpJUMDR1CbQoX99SBLTY2RUHGYTZmj/GZgsVqCqr4=,tag:B8Y8Wzz3bRpwaVtaoMzq8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
