apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: seaweedfs-s3-credentials
    namespace: seaweedfs
spec:
    secretTemplates:
        - name: seaweedfs-s3-config
          stringData:
            seaweedfs_s3_config: ENC[AES256_GCM,data:h2pC6izDrGIHq2ocJjqDyJXT5l1vfi/7k8olDcSEMhjohRY3kKnZSV85wP1E9ikRzpKWH6Zw2Vh4yI83QlM3elgYQKo3lUY6/+sO8VZz2asXpytpP0k6spOtFppNY+cATW+OhVFFr/b5TvJat+vXD9SV2w6tuUFtEL5LIfEdbxUuS1I4Cp1iAx5nNXWea8/PmRlmlJCB4oF6f//m37XZ8pMhFkIt94dvkMLDPJM7vjOQSFR2oRVRJVmzPQ4EceeothqWAka+Jonj/lLAphB25X4HF0nrIqoTBg1UFEzVR4cA8jxdQFKSdLQUH5GU/ImVrZO/ylhL6AAUx4564E8wrjIycMtfx+qYTYh6iDdE01MDGbSkGEixYo9g+GqiB+U5gnub,iv:Kz70BQkpdKmFdDsaB08KFFz4rPGGf7JO4Ztmo5wf7+Y=,tag:3hRtlD29KRX9hqTm72gYcg==,type:str]
        - name: seaweedfs-s3-creds
          stringData:
            accessKey: ENC[AES256_GCM,data:ii8e0dAHqgyR0TrRQd7PudbG31KVVLF9H7VD/3FU5ho=,iv:toTBmEMHM2tGeTX3PxWcpJndsLt9OTRaejXNUK1n0x4=,tag:ToTNzPwhgSIrPJOydGPspQ==,type:str]
            secretKey: ENC[AES256_GCM,data:QdPuF6oSeNyumK/wmLEYdaFfb1Y4hwM3b09Fs4ZmGUcwYekha5xiQQ==,iv:Bo0vOTw0r88hF5I/1JYjMPAEtLu2lTaVPLYiMNf0qUE=,tag:9N6t0pZUf+D0z9t92FGGuA==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcnRsVjFLbVgxTkVmRnBz
            SWl4NXhXdHRKZU5TU2M2Q3FxRTkwYThPcFM4CmxyKytvS1BjZ1RYdy85bzhtVHR5
            YTZrbDVDK2RkZ0tjSGd0YThtdjRrYm8KLS0tIGc4Z1NTcWhLR1FNZkl1bHhqaDVa
            d2dlL3IwbzB3bTVsVW91M1BvUFhhelUKQtX7OjfyxEYH6r+ITfASb0QhA7UcLFoT
            6C44gbvZy6ilPbsNS4qc4LtyrST+LZcSszEcVz7Hxb32nmKc9LGzfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T04:27:51Z"
    mac: ENC[AES256_GCM,data:gIH1F5fa8I7VVS4cR77rJRwNEhc1rvIMyzkmGsuBK1q8Hk9EBQxvkGg2i2Kkx/EGnU0a0NUFzGAvQw26MkWNIvH8qo3fViEhxbIKgSUKYptFpqOG1pegKtlmQJX8wT8qpBexfYuwLCLouxcNK/jWwoFcr9jZrHkej48y3UDDxcs=,iv:P8mZR9IJkSta1m/EQIZfSGWx4E5AJzGkffwAeoXCpaI=,tag:WqrNwZMD+NkAMNKMxxDzDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
