apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: seaweedfs-s3-credentials
    namespace: seaweedfs
spec:
    secretTemplates:
        - name: seaweedfs-s3-config
          stringData:
            seaweedfs_s3_config: ENC[AES256_GCM,data:lFAgoYo1Qxyf8aVPuwJJV/kaukqBNy9GGILJtMMbbEgGSabOH5JAg6kVzrlF03+H8zUl/RRUSnHVLdG2haQdEa2zb/g05tmBlPu0MwM9VkguVNdOBotg9J3uxMrxIKWzoRu7u/QSyJtt4UV557+/RppWV/6271IgRGl1EXkM8Iv95EsvQRzntmyBoNCp4cut/gkrLfqyAU3wl3Z+Dyc47Z4HzKO92+Anxyxgy8zPKO3Guvd2yHWq8o2J5SuPoWrcr90T9M15gU/IJ6mGF/PzSqibGew+0iRP9ALTlxKkUdk/V62ExYNecq6Q9KnvPygmFGy4vberUiu1otul0dlMKOx4L01S34mC56bPQPJUYDFdx7BnoTw7Zu7N2aSqvBdXmT2H,iv:ERrIaaxP4hWoFY/EkIkRvExHNTGLuG4AlnGzrdlGF3k=,tag:l0J7oQOHapM7rAi5V9kadQ==,type:str]
        - name: seaweedfs-s3-creds
          stringData:
            accessKey: ENC[AES256_GCM,data:tyEzEuz8X/19h5CLIsYiSRIMTj9eZXLg7232s2RdgyI=,iv:Vez9tHEShAY6jyoaH78rIkMmcjEnig9SlQUZ1NiClCA=,tag:mbjTB/3jbTgRNRq2GvDzqw==,type:str]
            secretKey: ENC[AES256_GCM,data:z3TliK65u0bG8W1CwCkhUhfuZBvsKuMP6XaADO6DyzpsJx1w8gq4eg==,iv:rYzXW3iws0lglmcVgqPcUqymDEyveCfKLfF2Fv7t7YQ=,tag:Cu9IEOy55u8a8p88YW2UPg==,type:str]
        - name: seaweedfs-s3-credentials-ref
          namespace: observability
          stringData:
            accessKey: ENC[AES256_GCM,data:rDSgUj7lQFzBZWVe9cYzP0ZdN+/LV+HGcUGtOXT4zOk=,iv:tT46WydiKq3cUOVG4j9w00yrHo3exzbwSzM/hBG/EjA=,tag:pwmh9Sd+57pywhP8PFsaQg==,type:str]
            secretKey: ENC[AES256_GCM,data:wxjN63aHGmoP3QMl6pVF0zM/Ia9qRqhOqsfnKScUKUJsQMKHsY9kUw==,iv:4E9hjOmX9rHtQAPL+WlZnO12TFudtfvWDSm8k1K0zTw=,tag:JDYfVJUSe6ZNTc6K1g8dmQ==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSysycmlneEtHOXE5R0dM
            UFFaUlZMZEFCbVFFMGdZTzIzK2NYMWRmODIwCkFSUW9aWFdwbnd6TFI4bTFGdmJa
            STh2SGUxdDBvaEppZGVzSEZBRjl4aWMKLS0tIFJnT004QnluSjVuaGxrcldFWG8v
            c3lTSXd5d0R5TEtyUndicnd3NHBnSjQKzjwkHX+gO2HrguAOV8mbu8WdMtstCaA6
            ZvzfZHEYE+y4CS/CyRhyqqQMFtrkYeKS+jJLvCo7TZPWCuxPqavBnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T03:44:28Z"
    mac: ENC[AES256_GCM,data:xkhWl1qeEU8KXmKVYe8/48VeMfyBH7HT3pb0bSeDwvTN1Z2j4AuYKgOCowl8rjJUb7CzTFIScTm3+HCTR4TvbwjqS3UcjnOCmquKaeHK9IDoF/aQEuqXJoxKCrCXR/sXOssLMdoW95omcQGEgXve/7gkXvs0zIJaOOuV2LDUvLs=,iv:UbdWXr4TahfHtp2cuaTGoVx5cIvdCjGrBtH4SigQ4YM=,tag:UpxQGzewoqP4P19CaUoo1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
