apiVersion: v1
kind: Service
metadata:
  name: argocd-internal
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 32170
      targetPort: 8080
      protocol: TCP
