apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-oidc-secret
    namespace: argocd
spec:
    secretTemplates:
        - name: argocd-oidc-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:p53rCx6IU8EBjw3C65Ua35O6/tdpwVBYglIgslx08Z3ZlGAR5euF9HsXW5WuYAyfC8yRdAo6nRCDTcd/oDgjEw==,iv:1q6Y3TCojjfYamuQxi8acE/H8NKe/mlLyDPtrZqNMlA=,tag:usGQwrmRLnpKFG4yl++BOg==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySGNabEdEbFQ1WkxpaVBk
            Kzd5WXhVQmMvSHl4cjhUb3A1L1JabDRIY0hZCmlRS0xrS0grTVBxK3RSY3ZGN1Zq
            RWYxWVJlWUVFWU83VFlJOHRDcmY0NmMKLS0tIEFrenFjKzFBdWpqQTNVcnAvemdN
            Z3BYejczN1YzYjZMNXVUQzN3QnhrdW8KJ0nFnEpxZZEXHaTGg1WXRm27M771KvCF
            kHqSNoEdMbC6qgnVdzpdS7a+tctCBZZbZoCXwC76IP5mBXmpLpZLKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T17:34:06Z"
    mac: ENC[AES256_GCM,data:15Uxa403FepmMuW6xkmJHUDVyRifkof8pX8nRgiqDyLQsfW6TQFgObJKmDB8xvzuXFeF7xO50hnjcJle3fEkq8gC48HacVHmy0v9k77uTpVcmSkjyPvuzNtJ6QfconlX3WlKUUMArR0aonAAROtfIFd2dOfiUgEL0mVF/VqDY4I=,iv:NoVTi9DrugPBBUurI5IUlDMoWtY6XXdrEdBHqh894os=,tag:wNR+QUV7XBlbvRS6cIB62g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
