apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  platform-hosts.server: |
    local:53 {
      rewrite name exact auth.local. platform-gateway.envoy-gateway-system.svc.cluster.local.
      rewrite name exact argocd.local. platform-gateway.envoy-gateway-system.svc.cluster.local.
      rewrite name exact grafana.local. platform-gateway.envoy-gateway-system.svc.cluster.local.
      rewrite name exact temporal.local. platform-gateway.envoy-gateway-system.svc.cluster.local.
      forward . 10.43.0.10
    }
