apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - temporal-secret.enc.yaml
  - postgresql.yaml
  - httproute-temporal.yaml
  - oauth2-proxy.yaml
  - oauth2-proxy-secret.enc.yaml
