apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: temporal-oauth2-proxy
    namespace: temporal
spec:
    secretTemplates:
        - name: temporal-oauth2-proxy
          stringData:
            client-id: ENC[AES256_GCM,data:kf2t0Dz/laI=,iv:Xb0vIbGC7fINrzVzJ6xfKDqFJ7uugudEt7jYhZM9vDM=,tag:UDMe2uO8bipoK3Tr4xOaSw==,type:str]
            client-secret: ENC[AES256_GCM,data:tk1VFg8mhpN3IyTzB8uSLLuJ8dWYaE6qy4PUHsgitzOwx3t4I6GTAsshX6kkimI5feMeu+cin6P/BrD7NiC3Yg==,iv:A3MTcR+/4LlYyBRvajO+IkR4rUGvaJ2XLA7U4wWOigw=,tag:yOgpOsLTOzRY98/UWSZ9pA==,type:str]
            cookie-secret: ENC[AES256_GCM,data:XB2ELO9YPA5zHPebdxNYReM3WsNZiiiHtILwywzO5rk=,iv:xi4cwos5JFFye3f2DyPRn158UWATwZK9PPrODnWWqxw=,tag:iCkAEDle+xLiGwMECJmH1g==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVmk2dmloTEtBYU1ETmZJ
            ajBqNUdEd1JIbzhUZjhCY20zQTlDMitrZlNVCk1QM01Gc1c3ZS85MHY2RWd1N0o5
            bm9UL3l1RzZoWTQ2NEtwbDZoU0JGeEkKLS0tIFdYNHNwLzhPaGJKcit1WmR1YVhM
            eVdYUFB5cFV2bjVCSnY0T29DdDF6ZEEK6Z44mOBmGbpW7RJpBG8Arpgcl0oSGDHf
            nk1WVEQbG2vtOD206+KCkgcmh1OuJ0XRrDfPm/TWVtLx0afP6WF2pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T06:53:48Z"
    mac: ENC[AES256_GCM,data:Inr4sL49e0HRa9Fxb1fTLOuRBOPLC1Xk/vHPH4bonZyjhzKp8lQgtY6gHN1yjYPSga1Bxd7RMXqnGgwoOl/2+jl+LmevSZt5LDKUluxuFL2/diUpuc4gBm1xWjboWojLm0vpDZkyJz1nNISVzJbKI/+wWJPd5Go5a0NRF1B09lA=,iv:YTpv26fo0MroaoEz4cZxKRwFic0IMJn9KYSkbiY+W70=,tag:1X3C/jDx+Dx7px1oPDSlJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
