apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: temporal-oauth2-proxy
    namespace: temporal
spec:
    secretTemplates:
        - name: temporal-oauth2-proxy
          stringData:
            client-id: ENC[AES256_GCM,data:BaqnT2juIy4=,iv:pTEtenn05D51zn3kBEy3dE7jQsV0GEhRAqRTaGG7qNQ=,tag:TaUF6ia6hPNlT8q/bMIH7g==,type:str]
            client-secret: ENC[AES256_GCM,data:m3987T1u6p49PMCF3gr2FyspV+ng8uIrsvBRC31wJxFEvidWCLV3ffI3yeHx+QKGAvHkZ/YtR3YAtIBVzrnj/Q==,iv:kEuRIibW9pH22TyUn0acR0l4TsfyaT5GIaD4JZ65ivs=,tag:AWj5J4ihSmIaENip4hpD/g==,type:str]
            cookie-secret: ENC[AES256_GCM,data:HsU+pYYmfRBpjdM1ZwYBu8NtWE9kKz4iWR5jqDrhAJbv66J7EoGX4f1elPE=,iv:GMQVLxdg7TwNAtw6tGy5sAVrA2qhLc6nTKi3HAZEr2k=,tag:sA155AYnxYx3B2LTF9jT2w==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q2orVVJZYjd5K1paRU8r
            U0wxYUZpOWNUckM4SWtwWXo2cC9JMkpLNUFVCmdmakhlTHdUVUt1UFBaOTVZRWov
            am1IR3h0V2JsV3UxS1ROL3dqVC9uWk0KLS0tIG5pZFByWll1SVdMaHQzL2dQbWw1
            ZDJCVE05bjRzS2UrZ0ptd0oxREUxblUKCOjiouLUILgi4NBP7HDXSg9uksVZK4C3
            ubCIwStfhswXJizaS/RmooB4qcPTbsd9WO+wAMeGFNiuBv5T/t15QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T06:48:11Z"
    mac: ENC[AES256_GCM,data:hdHUQ48/5EDn71B2p92nf3MfYcQqd4SfdPvuTT7OIYiXLNva4jiNRlI1hjVbb1tazZy2edeL4nbKoh2OEGhHqlDgReQWLtdpCtiJ+vyLSwf/7MSiOwErAwccqHxQHxZelVsU2DEn4oO6SNz/x8LJuwPqv4NtNOUdm33ROkKpW1w=,iv:oNPMAoL1d3xK3kQhzoyH/HRlqdPzgzfP9rRSN+qQ6vE=,tag:wnFeJzQVHt+H1m2O5QrjyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
