apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: temporal-secrets
    namespace: temporal
spec:
    secretTemplates:
        - name: temporal-db-superuser
          stringData:
            username: ENC[AES256_GCM,data:wbDelz1+0/o=,iv:kNcXGNpqEPJvhQWn2UVzleElaRI3pGiAHyW0ZvNkz88=,tag:uMCvRAO4R5/5e4+Lel31XA==,type:str]
            password: ENC[AES256_GCM,data:IFKcofYHQ6fKeT2t8w0T8Rb6BZ75T/3wgSFW9SnW65g=,iv:6ZWQHEkc8O8wVCaA70Qc7KVyNpY2Mtb7NZUwSZbUVoQ=,tag:7SfGRWZLeqUd/LwagFgZog==,type:str]
        - name: temporal-db-app
          stringData:
            username: ENC[AES256_GCM,data:EcEgLbkvXDY=,iv:Gr97NwCACdQXQNRfjb26QDEl8lm58XJbHUzmBmYagto=,tag:1sxXpi3gPdRezEVal1FQsA==,type:str]
            password: ENC[AES256_GCM,data:LCaJ2QpFxrLTwQnrIyrh7rYXfYRxDlDyTJrvCppLDw0=,iv:PC3WUSH9SsOflYGSETRJnslehJayl4O9iFnH+TCBJ+I=,tag:9pSdrrgOX2e+2kIa45osvQ==,type:str]
        - name: temporal-db-secret
          stringData:
            password: ENC[AES256_GCM,data:gZ/8DIG+rTAnYWX5smplQUYBI5oZZgu2ximgQwaKTJk=,iv:VtpPeS352xQY1+XjVvA2uzg36sMtruANbZn5/Bt2mpM=,tag:05M5QIMU0nFPfAv7nId9Xw==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VVk2M0lSdlJTWmNLR1Nn
            L1NjcHB6Nzc5TndJNmFQWHFTVmdhekl6dkZrCkxPcmkyWFJpc2dreTMzT3VMbzVT
            bmRPcXYwUStHdGlVMkJaSTVvd1hLYkEKLS0tIFkyN29PclNCU0RXZWZFaXd0ZGdI
            SFljSllqZXBha2p4Zk9EcG45UDBZR0kK/zReYh5O/LsOTSrGKi2eNcwmqtGZvFLp
            UDnRLdcd3QzqQ4HK3dijjP70F//KTsmTd5tS3WLVAN+pfHl9stph6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T03:44:28Z"
    mac: ENC[AES256_GCM,data:L96cLuNIOPP11wHejDZ8dZgCqz7o/UY91iLo0nyFuCeUaBkuMIeinGi3b5yPzlUhhXDgR23xUw1iQqPTjHD3xX7XFLwNo4jiu9OjTjVxKaFmpgCMEATtC8lwqYYJhnLBI/poX9Fmv5UfqStX6kdOJB056t8Dkrl6PUDVx96uu5Q=,iv:BDrtRW5UzyEE6FWw5rlk+amqEmOlmI1cQh4kuzXGjss=,tag:Uo4Jg0nMRO1gyMy+i+MwaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
