apiVersion: ENC[AES256_GCM,data:yMHEXg06+xTY22HvIIbjxYuGU2G3r2acitn6,iv:iUuNngk4ISL9w/bHjtt0jjkeBVePCWjhyBTOSCQudn4=,tag:HTiEp9K3KC/efwT7xwBiTQ==,type:str]
kind: ENC[AES256_GCM,data:RYglDBIey763DA==,iv:qmXVpVeVLKLXMFus9PTUNXa4wRgyfwCxObpcCqXoVEQ=,tag:kfJANUpsFQfu3HUSvBCntw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dH6DMByS0QT1RZihKmym3A==,iv:6x8QjauHsGtBvCniAFhMKdu7MJ3ncYThkSyiXOxNW20=,tag:3w3aRfC1SFk5RmPTA0mlcA==,type:str]
    namespace: ENC[AES256_GCM,data:hiSdbcLW+Bg=,iv:nIva+ZJUv5RtBUL8NALZ+3vR74XiACONLPQo3nxceBE=,tag:NFbtwy+S6aWIykoC/ElxlA==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:0Jd6l702yDsiz+X5PNsL8tyZmsEF,iv:ktYiAdNlcKuGUiCS4GmPvsNkTOsOnI+a3HxgmjRhxbg=,tag:agS6fL4z3H8tPGf9063ngQ==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:Q9GXHeD7FVw=,iv:NAwbrJTMXJWK4ZlyMT6ebVZlQqHDFIsioQyPpr/Corg=,tag:kiuTu/PdBOtrc69a3jBD7Q==,type:str]
            password: ENC[AES256_GCM,data:3ay3eeJJjL9jNAsB2xeEzZEBzlfPeEvCQCy/NfC7oj8=,iv:/2Qrt1FTnkQVMDLy6Oh6X8oWMp9nMDlUQk8IKo6Qpw0=,tag:UYXGb7l91Z6wFCfNTR6r/Q==,type:str]
        - name: ENC[AES256_GCM,data:L8hi+ountKZQ/ZmcYBWN,iv:M7ogO8kHj4U2q/3XcTeVisvpiIfb1eVsmjRl1kK1clo=,tag:OeCoOHxD1Y9IqOdh1MmHlg==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:a/BBONO4+t4=,iv:VjluZdM2Fvht4aRnl7WoGWj/TpCJPJX1mCa/RZ3jEB8=,tag:qAJn2o0PM4QZiiL6CfVuiQ==,type:str]
            password: ENC[AES256_GCM,data:1meR98X6MU13VWi6wseWWeFenhzQVsAKNC7jZ5GIRy8=,iv:3EDPmwhB6K3yL3LTUSXBngbSMAdq0DJ+Mpfr5yMp7JQ=,tag:X4U1s8pQay2yRX0ZoAs8tQ==,type:str]
        - name: ENC[AES256_GCM,data:O3m9EtvKRJp0HR6n0UNqW6xB,iv:isW+riDLAQC7LDrs63+8cdwQBgXgv3QN0HqUl3EyXUE=,tag:1O/upLInwaNYFPEvMvcdvw==,type:str]
          stringData:
            password: ENC[AES256_GCM,data:rXHr7V5O16ENAZvaYkVvykdXlz8UDWz/KryvpIBe70A=,iv:xwOPQU1S3W+WZ4Uv65UHjt8kKsSL5bI4pPDHHd0Mezo=,tag:cQ+jpezVewcban2NG6hINw==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQlpNUGxCZlZBSzNqa1RE
            RU9Qc0NCYVZXV3ZlanZIczhLMjV0SDhxdEFrCnJ6NG1ITW5Xdmw4ejJsOUxsWDk4
            RE1LNmpxWEJrTDV2MVQ3ZXFqcTZ3dEUKLS0tIGJETTB6UFowVWdMWFB2SGNidEhT
            elBxTGNwZGh2U0FmLy9UZG9aYUsxUTgKvvKK67RPiYfb89cKlk9SvCgUuUyt1XOs
            L3xwDdeXAsmHQMuwgZ6i7FA5YXNx4mvfFSOiJH9AAzeW3M7nhcm1iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T02:34:25Z"
    mac: ENC[AES256_GCM,data:rRe/+dBWr8pMgTtVp8TVdUQF5QSrLqu8SCdkceXXuB/JcZ9359EABeb6h5uK+SezDB/77lqI6HSpH9BAngJn6K9NNXR6o0V3+ljZeiBwNZTHvNxAC/Ms6nnKiCr9uFYlO7iTVNlsqS9NaiJUqhllxeWxTB5YJQAAfGOEEZ4gk0A=,iv:8dr7ySMJPNwOPKwj/ab0n2cchqyE5eAv/7oGV/ruoWA=,tag:O6YwMzi6EPu1H65g8vrsbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
