apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-cluster-local
    namespace: argocd
spec:
    secretTemplates:
        - name: in-cluster
          labels:
            argocd.argoproj.io/secret-type: cluster
          stringData:
            name: ENC[AES256_GCM,data:7gxHzAeIlvFEMA==,iv:hnAtx/UkOaAQ8NqHzYVLlynQFEixld3YD0Rl+RE6AoY=,tag:/crcGoM/w14fqjTGg6w/pg==,type:str]
            server: ENC[AES256_GCM,data:z3XtiIcVPcNndZu4QYh0fiSSbr5FxXvedq9bC+F+,iv:lfTNIgqp6q1xXAhc6mhPFl9gIpTf/6wH3dL6VFZiGrU=,tag:gjQ5cie8N30QyHmjb52Tow==,type:str]
            config: ENC[AES256_GCM,data:vdhUhlb+6PWLrpEGQ0EZEBHhwjtsJV9LjgP4H0uzwZYJVTDWJPs=,iv:123H4/xqIL5vlI3a0YSN1zDu+6AOyubFpayA5lQlvsg=,tag:BKLr1W0AMc2DVJDCzVglbA==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZUp2ZHJ6MWtSU2JUc2FF
            KzdsSWQ4V3gwYklsVkNkMEVNdTRSTDhpUXpRCkNTdWUzUWxQa1VNM3RJalVWR0Ex
            Y2xjeDJCT21BZnBPUWlpQ0tML0pXbGsKLS0tIC81c0RNU2dPUHhvWHZaWUNtU2ZJ
            OW4xWW9uRi9WdDUwVkxDRGVBcnFkV1UKLe4JjvP98EJGvJOVwqNzCzaM3w9NyKAV
            y3XS47QThKvCtz9z63PNmCWl5PU2Osff8pIvXdSgY1VweP17FeyElg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T03:44:28Z"
    mac: ENC[AES256_GCM,data:pvCfmYtSJy623mwBcL8r8Zs4CRNqaVfbR+yBYEyPttVxftvP6g50FG8xkz4SuUAY/YzI48u157S7hrHObw8q1uIZDjqrrPCCnFWnky7H1kRPu4x5eMGzHTnz8CCPy2YU6+btx3BIIjWSMd8yx3yZBOK5s5YPJDPZufTnycRKJgU=,iv:gkXEGjDRS+INPOVjQl2n+v614hVkwXtbf0JlDnd+N2M=,tag:TPD8ri5FsObgHgGXXX4ESA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
