apiVersion: ENC[AES256_GCM,data:dBAAd0oTB+qFJasTqbfbm3EpkkZnMNOJAYdQ,iv:dfkGt9xZ0HkBFHdSsRZntGQvWe4MXDRwiG3PJABni1M=,tag:FShT8oK0gPmcLRSWQ39Gsg==,type:str]
kind: ENC[AES256_GCM,data:cXGnWk6kdUqNDg==,iv:uNqg89o86NyV2VhYO5N+tbWj1NiVBvTJ4tFAgyRn51E=,tag:NcyDdC3euRBJ3P/YUVjy5Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w4y8pkf481U0uxyWzgQFS5bYc4qmrGo=,iv:9loSL2IiHDFoBXW611o/p/nbANpYLp0awKgwoxJyL9Q=,tag:bq0Blte5jaJvA7GV3lWDDA==,type:str]
    namespace: ENC[AES256_GCM,data:c/W7aJ3X,iv:9eEaTcVw62ZdQxqnmBzYfN50vVC/MbKhta047Jlb5TQ=,tag:X+d20j0V2+5q5OYBJEr+7Q==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Ag1JkSXZunyUWv6GovFg6l4=,iv:XKybbDYjNAiLbcAPgi12n/w9VP4sYm5NPi8vottuL8I=,tag:kFivntKDGSYF6AteBlQtmw==,type:str]
          labels:
            argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:YQ+AGG9KjP83Qw==,iv:KadIyZTa8TmS+JDOCmHlgRvHmAec1NvFP1UA9kbnV38=,tag:+Xn6aZrl5cUapP4VllE5WA==,type:str]
          stringData:
            url: ENC[AES256_GCM,data:8shzlTLm5J/zzxAFLPIaCUYhNunQz5ycIbvgdkrxPerJe0LcXFjgSNUv/Q==,iv:HbTDEYu37b8dlOnM5hfGGUk2QPGjq91nACdCbSbQuFo=,tag:52evQw5W0jcgmRWWiHvJSg==,type:str]
            username: ENC[AES256_GCM,data:DMkUzpFJexE=,iv:bqy4iBYe5q0GyKJAMW2ppXe4efGUi2lHpGOe0SmzJDs=,tag:YW5iIjdkSu0AgHLKNrZnwQ==,type:str]
            password: ENC[AES256_GCM,data:ePnKgYlH3W1ZnQq6WXKoXVb337NJZYM/H5fOPbQ0uHuDKjodn3IaHH3F/oS+wp5Q+9aOqlVA1gE+wpZjXqTGl5V21OdjjIzzmIVTrgpzTcuBRSqTx0xsPkcsJhuB,iv:2wcd+2nYRLQ/cu1XZogrFMmdif4KCvVYnQQ7z3UvFnQ=,tag:j+bZnWpsSRyN0DfwUYRQ1w==,type:str]
            type: ENC[AES256_GCM,data:hJi0,iv:/VY9Jvsk1/meBR2XaELzKOcIolCIMK0Poyc+sUIEF48=,tag:K/SG/p7endHOA9E+V3cTeg==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaHI3UWk1eldRMk8wOVdG
            MVpCWW5YTCs1a3dFZXRHWTZ3eXVyZE9zSzNnCkpZUm1MZUl1enFqRkIxREk0ZTNk
            bXdXVlAydFBRSUEwOUg4aDROUkwrVHMKLS0tIHlyMXFJc2lPRkZQMTFJTDRZR3lo
            TWkzUFRGRlFMeHd5dkdmOFgra0xOZE0KZYPe3kwxp3d8K/Ktt6HpfEbuBe2vJpCH
            XavCCUgZQwOowA5AvKs3Rda+L5tvWed2eUJlfSMzw19VMxP5HVOCEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T01:43:51Z"
    mac: ENC[AES256_GCM,data:lArBN8GT6Koneg+beBYTxGh7Iu+heeLOv+0T15vASQ3Qo+XJxoJMCu0+Zm3AhJTpYAI/wjxGaqOQG00wPhDNsQzUYbgBQahV1TV8XEPyr4lsxtRlgSyR+mGcUOoLNQDU8y9E9Y58v2nk07//QAlZQn0nLbuVNUbvoRmxRi2yno8=,iv:lJYdCY4AA/BztFgq+vNdCNAgnxHznLM/LjhaN6vMAZk=,tag:16LgWelk8tL+YzqOuxaiGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
