apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-repo-credentials
    namespace: argocd
spec:
    secretTemplates:
        - name: argocd-repo-creds
          labels:
            argocd.argoproj.io/secret-type: repository
          stringData:
            url: ENC[AES256_GCM,data:xuf1nQrHZ+VaxB30fZuODrqdbCCLdOROv9+BnyShnobRJv5HXdr7Va1OkQ==,iv:tXR1L2UomZgUWf9gQIk8gJVIC1FCKGesPFoPoZZQniY=,tag:Zoa3+JBiYbmOw0yeI412jw==,type:str]
            username: ENC[AES256_GCM,data:bjJps5yV5Zc=,iv:i44eWxtNXW6oBda+tgOGR4IuT9+reJ9AFc7GRt/hY5I=,tag:wtTSf1BO+zEN37tso96c8A==,type:str]
            password: ENC[AES256_GCM,data:dO9tWEM3IlroHxck0CN+QO9zbZN9lVw4sQCOiU6+ZGHkNRK3p8OhRP473ml72LYGj4RG2N1pX9zY5u7vsmCoNulhjHw1OwuIQzmbIRmxS2A6bM5TGfwPyfalsxKY,iv:ElPCdezdxf37dq4snT76fhqQVp3V0Cth6ohYpn6ZiPM=,tag:mEE066ujdtGJaKuGfQVDkw==,type:str]
            type: ENC[AES256_GCM,data:FFp/,iv:pId9YL9h/8rlPspDovE3JNELLHsw4O55yIXc5L4g50Q=,tag:BhcAX8+uPNpjud5iAC+rXw==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcTRPU1l5Ukg3OGZDMmxC
            K2VvMVF5UzBsWGZOR2JoNWhtcVZrano4VFJ3CnEyZUZwenh1SFFNVTlKY25xV3p0
            N3I2NDQzTjRZcWRkV2RNMExCR0l2R2sKLS0tIDdvcngrbnFCWHh5SzA3WHJTSytz
            ZXF3bUc5ZUgzank5MThTVVBva3pHTmcKv3Kv3SoOyo+hWkCU0aMDowiFzBEpvgpY
            u/Cv+saP4ZrOcWJh63kRQ51k47ATEE9VG5+XZarIxpx4xs7DDscM/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T03:44:27Z"
    mac: ENC[AES256_GCM,data:b7PwGxjhhokT19NbFigrt4jxTJFboIf/ng6yJ/EZyXbfD9CteXNBLeyM7kUEQZejFZJGIKzlFo29avE6DQlceN4bxrTzjO+EeQ6BR3xNiuHhq9QKl2pdwG9AEkpcBMl3Gn1l3wg6Q7c+fEevj8e0VzMmKIk0s4dHz3ghCxBl8zs=,iv:t9UnUggupOFc9pLUbD5TY1vZ5ymc5dW6EgBHcDTwEjs=,tag:rNOmh+WnKtfL4obYjxcFLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
