apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-mcp-pat
    namespace: kagent
spec:
    secretTemplates:
        - name: kagent-github
          stringData:
            GITHUB_PAT: ENC[AES256_GCM,data:mWijJkhnacwwYpiRpGUU21o43xI/bXGNxfhqhM8MKz99CXM3vXZ5of5B5T0zL67IPbspEgBV8Qihye46PjWZ/vfufOJcNpXhUSpRUEU3YYaMJ0zeavlRWJNn2iEk,iv:W/O/kE5k5Agls9HmokpuH6p1qBPQV04gpouZM3HlAyA=,tag:IElOJPxAbkjS5TXRMZUjMA==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdkhjN2tib2dpZnVvVjYw
            TUV1UVpDdms0c3pKZjNsTFN2V3prVmh0OURnCnZMZ0l6YWk2UU5LUTV4S3BWKzZl
            bWxiRDlmRytKcFpkWERMU3NmKzlDT2MKLS0tIHlmKzc0cEl2a1hkS0JzZTBtVlJM
            MVplTU4vL2pKYUs0ekljUGpvdFIzRTQKZz/DltUlP/h8+Y5EffdJYZ7X1BYRRLWU
            uwV8umMjB8+D11Pwiv5B8jaOsaIUiPUXU1Vqe+Tr9qHZ3QpIECq1cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T05:52:40Z"
    mac: ENC[AES256_GCM,data:DbXHmL9E2pD6xIDufY9CnyvVd/xsdiMZEGoFAizF9GZwSMsKT4LHTAeQG9j5ngu7JY8Zzq2kdA1DXTYCl3Zk0bby4lUq/o9WKzfSjgIoyVDJToAUbgxYGlocMDUgvgsfj2J+HLAUAfLxWVwiSODqCNHlLdlufvEe+IQqLnK0mlQ=,iv:r79+XFZbV54NQKLHfd/pVfPgDStpyVpmKQ4AZwcgs4g=,tag:tkaGpmfbU8wwcrqpdY614A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
