apiVersion: ENC[AES256_GCM,data:3rZbti2i5Jc5S157x5N9LMTPrDKpn1Xr6pYY,iv:wTtj6yETnlAjG9Lp67DJqe+J16mvUBAOokZXrKUItWE=,tag:yikSawxNhFqlb0dWfA6Eww==,type:str]
kind: ENC[AES256_GCM,data:WX7kRweB4vc6zA==,iv:nm+xIyLF9SnC6Sl1lB+TCNX1Xdtb8RGvppdEUl7aOcY=,tag:3dKL/TKL0qOBR6n5KBL7aw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oWvd+zUBDCajf6sor4Q=,iv:OU/A5qIuOO+coBOSZy4QGKC25Q0n3JRUlhjr4xGUstA=,tag:IsTahNdqz7RJbVBvT63KlQ==,type:str]
    namespace: ENC[AES256_GCM,data:Ulmi3fhr,iv:R2A7F1TFAHNzhdNsnl+FRnc6O8gbmAOSjjbwh59+ymU=,tag:dqpWb/o+R/hIc0sSAgTRyg==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:nJ2C886AEj8+WA==,iv:KfVr1BBnJ+tNejX7V94zTkz/HBseKCcU4OuGxpSCbGs=,tag:WRO2914SaeM5fIZZl/H+fw==,type:str]
          stringData:
            token: ENC[AES256_GCM,data:gZSVoJTE/ib9v65437tdVZbzLJ+lh5ZJ6Cf9H5YbZSmV14InMjhoOxnQY3fE6YLn+DYQ35ZDrFzo47Xdqq8TFtuYhykXZW1Amly90VwJOqgg4rcCrakWmifMfqle,iv:ukuervVlk7sVmZCDlhweG+A35h2LZOe4skd4nSIBBD8=,tag:nDUz8r38urW0eewzck8f7w==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QUNhalZhRWNtQ0FPQjBJ
            VHp0K1RDVFlzVFFWeE5GSnp0TFRsZU8wT2hzClY2ZHBGZFBLU1ZveE1xQVFWeDhq
            NDk1cFVSTGR1K2Q2azYvUU9ydjkvQWMKLS0tIFlDcnpsQW9OUXFUNGhCL1hkL0s3
            TG9TeWJKVElGT3BSaWt2cFJsc0NweGcKNHbLl7gmcdPWsUpqHq9+bCPF8xtGAXVJ
            lUL482Y87R/8XIQ7SX8nNVoA2dVWpJ04EY6ifLY4sT36Mq08OwhQcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T01:44:22Z"
    mac: ENC[AES256_GCM,data:L0gwQdQ8cFqT5XcJ3ClCHBnf94gVg4cMA20Yy3fOVjGetlEumJ/pvgoa6TLq3AXNgvbdk/Xaiwq+KAWczJVRAKG08BX9/NTHlydOOI8EvagskWAiYhaT2yc+xDuTOENxR8InzGVy4ehD2cQ7YjalwPObbP1Hs6lN2VDSMZr/m5k=,iv:HBTKZA9geHPs/gkjGWi/XPQbtrRfy8RGFIHS9l5MCNk=,tag:TeJrGWuUTBprMEndsCviSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
