apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-mcp-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.com/Matcham89/AI-powered-SRE
    targetRevision: HEAD
    path: agents/github-mcp-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
