apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://go.temporal.io/helm-charts
      chart: temporal
      targetRevision: "1.1.1"
      helm:
        valueFiles:
          - $values/apps/temporal/values.yaml
    - repoURL: https://github.com/Matcham89/AI-powered-SRE
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Matcham89/AI-powered-SRE
      targetRevision: HEAD
      path: apps/temporal
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
