apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-oidc-secret
    namespace: observability
spec:
    secretTemplates:
        - name: grafana-oidc-secret
          stringData:
            client_secret: ENC[AES256_GCM,data:adB5O1eMPKnQRxFuKX7K1KarqM9IpEjL1RyQm8W5HzrxMd6ukQ6FzkN1bZsrZZWH+KoUcawhhEmbeLjzp4yLmA==,iv:Y8gCNkE1xEv3Z8BzB0u0v+FirQ02qjDWfdhAFgffPno=,tag:qwoaEjityBPXKpImW7UQEQ==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMkJkNVB3QW5Yd0Vyam5a
            d0owQ052aXM2cnFmQjVjUkxPeE5lMWcwVHpNCkp5UTI0a3pTZG5nZUFDNDdpeGwv
            Tk11cTArSmJoODVPdXZhRkUzMTZFREEKLS0tIFVQOGVjc1FhVkdXY0xoa2VBdXl0
            N3IzYUg4dGVzQk1WMjlRaHZhdS9ZWG8Klo/aFwuZ1wOaBBXlnDuVquDhg4fARR3v
            uhNh62MgRIR1FUQAmbo8smW5U+rciFp/HVfqhwjDPeJwC4GBH1/0LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T06:48:04Z"
    mac: ENC[AES256_GCM,data:ly9Scsvjlb0pDtx+gZMrThi+YkOBNzIRUOc0dPJK2BIj87MixGrdEksKHulnxc7s58htD7rEdPgEUE+G5mx8ahtmUAyYCV2dvTni4V1S6pgvB+AhDoxEZM+cNamaX2zG+qlJcYKHTv55ciVXwpWSnItQg9VB7EBeOruBQLt995s=,iv:chuZHEa+TcYZlCIn2Oz+4hLPJiY+C8zsJnvOcWYRSao=,tag:4K0+GeDJdkyCKxiWwswt4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
