apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: observability-secrets
    namespace: observability
spec:
    secretTemplates:
        - name: grafana-admin-credentials
          stringData:
            admin-user: ENC[AES256_GCM,data:SygudpE=,iv:/YZ6HQByy61+EPC4Y0ZNa/2g4r7+fktnDwPoqzFdQ00=,tag:jrJvAf1D16RFj9DPk+OlZg==,type:str]
            admin-password: ENC[AES256_GCM,data:LEQ1r10Ys/6Uv9NnpYAMMVXCnC9HqlnT8ojsc+rPm7Y=,iv:Z0L4IH0/zm5ac4b9Prey6xTwhv5+Kul92xz3QLKjdmc=,tag:x7rhvRFLZJ7lgkEULr8Hxg==,type:str]
        - name: grafana-oidc-secret
          stringData:
            client_secret: ENC[AES256_GCM,data:0MOMlsOj+SxRV8XY22WFrsLgkManuJzx57OadhWluEi6rESQwRzUgA==,iv:w+q8iZ/drbIUveDJUt40J1Wq12DN3aoB6C8Qld4C5yQ=,tag:WOyQHdZZfm0DkpFjO+TXCw==,type:str]
        - name: loki-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:giVAZ+9/OnWJdhQzUCOEaCFpEqdxYvNjw0NHNDJGnUk=,iv:DQhFxuQxK3jA8gguu5RVXygMc+ZAPJ0TTCEI6ILFNHs=,tag:d3eZw/SazvKuWnkzX6WhJA==,type:str]
            secretKey: ENC[AES256_GCM,data:gCmSlyM2XfV0C5SoXdV2I0QRY4J3nD/WvFp0erGlnkAn2Xb6fn4trQ==,iv:+fV4mC2V/MJJ5wCj8EUSLrhW3zU3vS814es1Q8Krtr8=,tag:AnM8S3+xCzu1F4wK5d6kpg==,type:str]
        - name: tempo-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:vT49G3t5cR0cWozJ3rrr1+EHY61Ry3eCpYpi+HgY7zc=,iv:wcU0tJ8fjLggrUA8kCL2DeZclqxLqLPf1qi+QZk4oH8=,tag:wuFEYDIfvzBlup4fD0w5Tg==,type:str]
            secretKey: ENC[AES256_GCM,data:HH4HC2q3DYCKzdyYuyf1+QSb9sIEKrkM9RcPDaP1XHJAHdqu3QIJ3w==,iv:eKXGo6zUNnRhnlImWaEU7QZB4FCzZiIOFvmls8t5BBc=,tag:ixchhfLdd42+8BNikl03dA==,type:str]
        - name: mimir-s3-credentials
          stringData:
            accessKey: ENC[AES256_GCM,data:QABM5c2BE7O+XWjsua5HX/HiVZfMNg/6O8kqEzD4aAg=,iv:qozAi7dnHqKAYzYe/k45fcHQ9LqHmwN42psVQ8aVWpk=,tag:/UvZSzguyKmm9NgSPn0tvQ==,type:str]
            secretKey: ENC[AES256_GCM,data:FIGkVguzrpDXa8YZAgdnjh8CCQm83lT/EdAIkDcREWDxUWQhbNYSxA==,iv:+d8AKdgVWOZHEUIQNi0ngIOv5T6e9ept2p7HsdwIBm4=,tag:9c8FINlUB+kh9XJIYk+3sA==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVXlTQ21jbzFla3VNVkxO
            aDBYcTRSN1hjcjVWK1FmUUlkckE2aDVYYVN3ClJETzQxMHdIdG9SSU4rdWJIR0dQ
            czNHYTd5V0o4UmFKVEtsT0YrUGhweHMKLS0tIFJ3NXdBYml1ZjI5MUttR3BTZ3JS
            Zm1EbUVQN09DSjdmbEZVN0I0WVJwU0kKgi2On7JYwSkxGpr3ENY8doqTlrRYUK9P
            JMAab+G0g5wBw7FUF3oVyKfrjXYY+u7IQgwKCGQ/uiFgcWPEujIWUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T03:44:28Z"
    mac: ENC[AES256_GCM,data:lZyZCJURkmho9vJd7lnigMzCPO9Xq8K4fBo3W2iF18yXSXDfQEWanY/05x0JeitXSVcVfAxrBbQ7bms37V+O1xE0gDttYJMDkz5653AI/s7WVP3ZPtUuT4LGcDYnQ/6Zmy1ifzdrY3vXiXKP6kqnDS+8/iWpa5uccYtWk3eDL9A=,iv:tJuJ4m4nGGgPBZWHGPXPPDMEVO65+ZXLWXcfHBwvUsc=,tag:eru9rOBsRylf39YLNDwXug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
