apiVersion: ENC[AES256_GCM,data:wjljNOQ6qtkJ+KHsadOlt6UcimaDbLE9VVHC,iv:g1qBU11bNwZgJaWDZaopjnE1DhGVMQJsGrQTVS6/KEU=,tag:Ote9k6n88xv/7RKID5aI+A==,type:str]
kind: ENC[AES256_GCM,data:h3xFpGFR37bvuw==,iv:Wmn4N0t98c1tHs4/ai8ecOlsNtvxQ6tocdHekVQyEYM=,tag:hcsJO3Cnf9vaPQ6FROI+3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zIQuUfI0hGoWVjfcdPG4LYbVqc1B,iv:O/QhGqSrMOtInzMO3do6EdHhPfo8whGpdd7RbYjWenQ=,tag:IQ0Ol8K57UduL9mU5B18/Q==,type:str]
    namespace: ENC[AES256_GCM,data:k/FL10z2AMuIXB3+Fw==,iv:9Z6/kk6ePHkzYoXzh5PUjn2f+t2kzJX9onOBVuRcYAg=,tag:zTbCqlPs+S00plPOqXiaPQ==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:YJ8NBYajcJe6w6CnIJIgnD3hYCzYjK+K7A==,iv:igY4oMiiAUP+PqjpnEGZf+VOTAgCFAN1LMn6YiB7Msk=,tag:gQxFIJK154m0eZ0mnAPsvA==,type:str]
          stringData:
            admin-user: ENC[AES256_GCM,data:XPHOQgo=,iv:Q9CSqVAejAjq9PdJnmEBlslkWJL3UGZmldjC+jBycSU=,tag:FEzMuikvWh4ui35ucvhnMw==,type:str]
            admin-password: ENC[AES256_GCM,data:8f6iJ+/CT3Ka9GL4kQHOl713CH+Y9Pv7IV2WOi2r1eo=,iv:WN1Ni+5ktH5Ua12bgN2oARNUC9b/drPm+SfYh4pR2LY=,tag:m2ODsAFLQwplfOsECA/YGw==,type:str]
        - name: ENC[AES256_GCM,data:SGVmXWu0SyPU16cCuV7pPM0a5Q==,iv:/VeaiKamuiAY4NV+mF4bBMXAnDbgxeG9ZXSsu1lpas0=,tag:bfPQfSf9xQ4Qs80vg3XWwQ==,type:str]
          stringData:
            client_secret: ENC[AES256_GCM,data:FLHsSj9R3FiTXy3yqYYH4jHnYeybV0Xp0AP9qobPsk/y0pO39pnuYA==,iv:5I7nSxNoX+nxixz1ZDst8iLRxkaNdb86ibJzkQoSKlY=,tag:BkA1MGp5dsqXcf6QSp8vRw==,type:str]
        - name: ENC[AES256_GCM,data:zxS0NpPJtWjX/RU0ESCZy+bwDQ==,iv:1s6+ZZwxhQg5ovYU2tcB59yHzdpn8HM7btwoa4i/gGI=,tag:PfNFSfXFmZZVd5LLPzgCGw==,type:str]
          stringData:
            accessKey: ENC[AES256_GCM,data:mGeRVUcVhs3rTjil6Yqd6uSTmJn54D7fFCmCN7jKPBM=,iv:dcu4ixyGamy+wkv/3TMuBx9hBXIXLPevrj/i8MicnLY=,tag:udYJZOm/ghUZ06R6fVvWag==,type:str]
            secretKey: ENC[AES256_GCM,data:/BDEEA4EqZ1xrDVwgVogTFh1GnSYxibNQSvGE2jAW6xHaZzs0SWhgA==,iv:K7QVIubppG0ZsJphKL+aJS6st7bnlgKQcMvCHnXAJlc=,tag:Br2URTEgq2i701seDfvUmA==,type:str]
        - name: ENC[AES256_GCM,data:DLABtTYFPL44qjXA0y+n4gbX6X0=,iv:YxWVttFRGVTejLoTxNepcVlv313+QQhoRWXWYe7nJp4=,tag:Xb0QH38ct2kCgJJ3LUluNA==,type:str]
          stringData:
            accessKey: ENC[AES256_GCM,data:ZjFJq1zkWLTGWyoi9gp3iTbkqr0jzGAPJkzeVVN9F3Y=,iv:RjthqB9GmcB9uvSp0Kb2//MIp0GDRRzcpLpi5OD47Wk=,tag:louPVE2mqJdx2g+bj5ONtA==,type:str]
            secretKey: ENC[AES256_GCM,data:YqQZndVRZueFQIbAIGWf2iiFoOFu7S91YMtgbvpP+JYHfmg1LSjq/A==,iv:nrPZ4yrwT8MRIghfTbCvEvHIxg+pJaXcR3S78NLVJE0=,tag:4Lmt/rouCHHIScFTsLxtCg==,type:str]
        - name: ENC[AES256_GCM,data:LcwVwD580Vf9s4RrNKQvrfAmARU=,iv:b2Y3iMwPsAAifORzYUGkXmp7wLtPYeBPghm1Or50bPw=,tag:5dvrZ3cZqpIUUltxkRvFlw==,type:str]
          stringData:
            accessKey: ENC[AES256_GCM,data:HBwljU9/c+5A0ILHqQvl6JnzBR0uKS21qyq9q5PXBJs=,iv:Jsp7M0gfz2gg1j/kbaqoA3HfqNYc3aNLWLoCD1/jl8s=,tag:bOA6oOrKw5SoS/Sx4iaxXQ==,type:str]
            secretKey: ENC[AES256_GCM,data:ahIxl6kzlHFfI27sKaiooXrc4X+VTCy9OBE6LvqOO0sEkF3b5wWFNg==,iv:NT0mdWnRI7+emye1k5wXLVxNW2epiyxqi0CR2f8Ozng=,tag:EX0RYGfk+PVNJdvFTWzIvQ==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleEVSYnE0aFg5RjJlZlJV
            dWF3NVdoQnJQZWdHdDhHRWFEdFhrc08wbVdJClN4NUJvVSs5ZVN0NExyT000L3FK
            MmV2eWJDdklRRWlObFdzN1FqSVREZFkKLS0tIG9WT0hGZTZkaEFSY202a1VvVjBP
            cllzMXNRbC96SFMyVFVyUUVHcDhkL2MKMLNpBT9wGwgHmjCtfeqAuqp8bOz2eb5g
            PnqpcO6ElI9TZCn5cl4PR4IvuPwe5s6SucI2lYWfHSzCkEczis6S/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T02:18:51Z"
    mac: ENC[AES256_GCM,data:tRG9wJuVur2lTxgKX/F626PvDsZWDUauz10dcwxEd2/czQt1YTm+nzArLH8iRWrvzAUAHTO93iMjwVIADv9tXQzr4NvfzF4o+ld1hW57nb5i2MoeddW2kXsbk1Ld988bDdhpZ9YrNsQloTyrOYpoJ5YNS97CViF8CipPH0o1HWE=,iv:BRrwKUIPpRehRif/z5nhyWt7N/vTn6Q/6UgISQrPnUQ=,tag:y4F/kgwAAQBIdOLyxqhkaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
