apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-secrets
          stringData:
            #ENC[AES256_GCM,data:xDmoruezmGJKAb21Sl5Os4qlgBtkJlnA56EYlVuR8gXxUyUS0QFwXBySntJUX8e9J2Fej/drdvxNtSNby5BG73rebTyBww==,iv:8wNhVbtqq+aQSJkzT2QgRgeO5cGAMP+LKoR7TGiRI1Y=,tag:XBv7woWrkSExaLaLrcm78w==,type:comment]
            AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:QBN5059iFqlZM+ckLSgji+oCud27o/hBPZXjdSzb20MFG7U57S5Iqny2OqKmXRkzAF0=,iv:sPqZtrT9ilXQM+c4pLZblJ06wc6dqXn7HM8QQpNC/GQ=,tag:TNZbhLGjApQA7crbirIBgA==,type:str]
            #ENC[AES256_GCM,data:aGG8XnF1OVFrs5CT62mv3Cx2F4stFBnsjC23Twwxnyu3fmhGGSTYxPaDxuz1YCBXFKH4orQBiWfCATYT,iv:gy9qAhPO7BCBL8vAeNmHOOdti+8FHIkoJNI6IN4lq28=,tag:Ds9z5Bc1t/TzYCe+TJh0aA==,type:comment]
            AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:ZY/Jt2g/ciHFgUK2hBCFnZBU8DXQFk2ywNneyp0=,iv:VQ6HwyQx6PsZROSxj31+3e0KxARfrmCBxrPtkcEzhY0=,tag:F+Hx0dUGKGW+oH3Nd981Gw==,type:str]
            #ENC[AES256_GCM,data:PbP2M89v5DJ3Qg9f7zP1Y34IlbdUcyhcVHt/zIZjoe90llZ0oBdyfbg66+UL,iv:nVua7M58QvjtxZs+X8sRA2k+956pf3I4uPbZNQqUroc=,tag:HOQtmAZN67goVxgyUHIkWg==,type:comment]
            AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:SjC8LO5/updgI/u51z2DgUmMIz1G/jY=,iv:upNRfNJw6cLc7ucXi1G8DuU0MO/GMlyd6OwFMJ8OKwQ=,tag:/7eExsgY7G01vh8DFTpYoA==,type:str]
            AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:XhLAir3Y38dxAzO9n1W6DtcBtjjJihGFl6UuoVW0yDiLBY1glo5xFyBH6P6JC9MUNEP2eYiSoMDTvqEzU32MeQ==,iv:AKtsA6H8J/OKIJVRMW6B5ibBCoN5me4y56q6m8b4/Bk=,tag:M1mRMWf7UubufzrbIZIiRQ==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bDZuVU5Td2xnaUxRaTlV
            ZmFjUEd0VmlVaXd3b0dUNW1GM3JDWHVxb0dRCllBZVczd1RCQjhEc2Q0a1IxQlVt
            djV2cjVoOSsxRXJOblhRcWNwa0g5T1EKLS0tICtsSmd6K1JlVmpBTG5FaStDaEJH
            M1g2dURUU1dFT1dHVXRrNndEWWQrd2MKbT7xTZ38iQivzoS2E3NBKp57NFnxQExS
            UyqHnOIUqERJfi5YGNyDbYnw6mCtb7MLaqSJEVfnba7oNGilu6hhCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T03:44:28Z"
    mac: ENC[AES256_GCM,data:MfLuqbiw0c7J/oOvrD/2ENBH8M+sYJ7VdOuCFrkZ9l0YKGI3BmJwYALF14KDBDlwc16ZmgniMhrmcxJB7taoi57K6Ko18ZRXC3xKODX3EugIxLcVXRpRAUauYhIW0M7ov/SYXx6K2Iu8m7HBVvKFoigXT4hq+1OwoAasBLsPUcI=,iv:fnHpy/BXuT290+9HXOmjMpVIqwTDFvAETRLvozwrMvo=,tag:xYZyLoaUyqloaos1NkvAaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
