apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-secrets
          stringData:
            AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:k+LrieB0Z/ByoHur6EibTfHADIIV6f+l7L7n90Vou1GFO1WziVzlxSiaSY249VDVI3M=,iv:+T4M7drZ9w/g0TVhVcjeOf9NMDizL42g8SgmmKZjxGY=,tag:tHg+9+xMVMZbZAnRiyR7fg==,type:str]
            AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:zp7i803L2Ptk0RkVXxc+0gJJyF010mhdf6euWQI=,iv:vLom0Km4Wf2p2yzADBTioUNuaXgqM32k8IFCeVRGd9A=,tag:wuSLgHA8ts9i2l4yx++JPg==,type:str]
            AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:3915rYTCv+2qzbfBTChBw/GnwZLdbWw=,iv:Qv6gIZB116K1Ac39zf0gScpVU1weOk28iq4o5ixfp0Q=,tag:vZjRhQijC+iz2uoXDvGUtg==,type:str]
            AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:bCxPWhD2uGu4ZpGl0lSS8ArSuaidBn+8C1rKhLSjCsW2zuT+x758jrVPzNTD23OY/79zEC0X+90h5nB6KyMCRw==,iv:+sI884XIgi2FxEy2Xlv4xPCai8MjSv5zbq9kiP8gGUg=,tag:Vlop9TU9p1X9Qk8ug+od4w==,type:str]
        - name: authentik-db-superuser
          stringData:
            username: ENC[AES256_GCM,data:3oVN9iCU/7A=,iv:ZoJ5DIYGUCmTHeh/kNmUGmv0ueCEgkiXv5OGGHsZmR0=,tag:UWpvKEdt5WQaJoCIyoCeFQ==,type:str]
            password: ENC[AES256_GCM,data:63uSlHj9bSC3Hi5c+DZ7we0SNAJR,iv:/2XWoT7w7bIEmdG56gwXp00ceKPzZGO8ZOiPjIuSNL4=,tag:y4mc298oO8AMZqF1q8cTxA==,type:str]
        - name: authentik-db-app
          stringData:
            username: ENC[AES256_GCM,data:nje6dkGE29s5,iv:4NihwagR+ksfVjv/15EiB3iKbPQ91WofLINIbqolras=,tag:gTyl2jisSMtFzors/8r9rw==,type:str]
            password: ENC[AES256_GCM,data:rlxYnIZ/AIb7Uq/jqb3Tao8ATg/kM4V2LengfzE=,iv:mHZeGYifK/r/Hpu6LGs86fbOI2auO48QadSKqcYeWnk=,tag:fuHak4l3Bc2H5oo2QHZFMQ==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOTljalhvRXNYbXVUdjFI
            bDlaNjlyUmRHUnp2Yi8vbFBiZFdqWjJkTjN3Cmh3cHpESlpNUGovRlR5QzU1RzlC
            VEQxbHN1NXI0NVhKdHdOaWpyOG5ITHMKLS0tIEdVMm00SGx6NVN1ckpaUE84RzJX
            TmVxZ0s5ejJBdlNzblJTamk4aVNnRTQKndROWqad9W/FDIf1ohhKaZtcZv0zk+Jg
            p4m6ka7QLwbIE2/DWTckf6mR9bF3JhnsAqDJFFNoN+Sx2D8EE7YNJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T04:37:26Z"
    mac: ENC[AES256_GCM,data:un+hA2KYFh0QwJcJOqAD60GkOUzwEvuCxMjk6uOijhHaDgwtsYFKiCee3BGiKU7PTxG0mX8UyfeUPTDY/nWjhSAXCYZ89TJhg6uNQJSR586Wp1uDhDBG5B+eqiUx+kUpM4iA9Smn6wssPCdL2F4SWyBhrCJiEwwoBUcE+96zz4I=,iv:aBFibczRjz8VjF4FDtFltC6zICOeMUQR6zMMnaWKWRM=,tag:usAxDF3tuf5nPkNa0tLV6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
