apiVersion: ENC[AES256_GCM,data:ekQf6vggWb6kDAPOdNLAn43B+jO7EfRsDEOx,iv:vbaA2BMA/muYvWIx3oWt5AGiC0SOyekrJjm1/iK4GTk=,tag:TUlE++g2ip4ECKqFVYaGfQ==,type:str]
kind: ENC[AES256_GCM,data:DJHxHlvC4NrVeg==,iv:KV/IKedeEpIDA9Lur11C2R0QKg3cl0tUfuIzu6sZMTE=,tag:hCjw2/uc2Y374nJ+gWmQaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:APqFpsiazM+FLI+fHMopqCo=,iv:Zfka48/B+IqVa72PVIFVW+R4VyZjQ7CtLk4J2akPhXM=,tag:oHkT2v0aDj43keKzMRv8Gw==,type:str]
    namespace: ENC[AES256_GCM,data:MqpxG887b6z1,iv:C6+IKeWvvhwcZ6BhXrjlwJn9Y5mBLRSR//lsDvDDdIw=,tag:UPf+BT81igFRfjleLC9Emw==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Zb5SQdWREfutNU+ylYzBQfk=,iv:vvjCBZwiVZd2Gf3Yeht+X6BdqHEY3tR47HkpeK5FJvI=,tag:n6X1K2andAl1Va2xXoOxAw==,type:str]
          stringData:
            #ENC[AES256_GCM,data:N6zCxDApoibrT3hR2u+l/CrG2ul5sdxMV/Hk1FgwUFb0nzAfHBcKEeyNx4aHbcSaCjE817Xo2Jd553NyEc9nIBzOyNUAcg==,iv:NUJjyyqJlZe1ssbx06y/OiiZc/1wN/3M0Mac86sCA/8=,tag:2uc3KiKIM5jPJGGc710SLg==,type:comment]
            AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:aprBk6kJQfzP/Bx0Dz4y5Nm2YgSk5ofx7d6Oucg7xU4Yf00qldFwvU5b/d9sK+i/lT0=,iv:OkUJX9T2ED7adkI7M0ZOCmKjN80S+2dyA+jYnCn/tBM=,tag:KLwRau6+FWURQ5aHen9P+g==,type:str]
            #ENC[AES256_GCM,data:OE9WgpHe2dvpfvhstO2E5s97EOMpYZXNPy+9YhKUk0qz0V+CqGTezLlc6qBpIgnQ1KeYUpVZ44VjE3T2,iv:wQwQSpAi6O5USKx5BYVQ7afM4ABXmG2W2KdxI/XF/VI=,tag:hPgoBr78R9UbfFo/jlcYKw==,type:comment]
            AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:gn8emEPlop1Smkfe3LSScjj3Vqyk2r9Gni5hDp0=,iv:/m9oGfA5nS7LznlhD0Ec10roTaLAy9z2HsrHn1xUhIM=,tag:ALZxprjxBmEfOIZWs8BvvA==,type:str]
            #ENC[AES256_GCM,data:tZy4yHsmb/9e3XSmFmfEYF9QCW/a1NUdCMyx+TktoHkooPbNOkwTXK4IMdhL,iv:8Ffb+aYpBl3EhS69eRg30TI0AkBsUzMndpPp6RUPzTw=,tag:jGwgKEDZho4p1WcK3Zqpkg==,type:comment]
            AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:27K5cLP/GaZVB/Y0Zh4DV/tZuaMohA4=,iv:I7xpMJmxTZjTI2U1tSVXiVEmYkXgyZgnY0lvv+P0Huk=,tag:LtDMIVeRreAjK9DF2VzQXQ==,type:str]
            AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:+vI0iL73xywKev0YETXCAmkdRFB1m/YGci4qLL0jxcs2xpOfqrri5MZLTiEPn8f49M5v9X2J3Chioejbo2lGzA==,iv:4g1El/E9vctfot3uLgmIbOvvw3WxOeLQd0Ekk4Z8PbU=,tag:thracb5BeofkVQmNiw0+Bw==,type:str]
sops:
    age:
        - recipient: age1jpjljdr54z2929pj587e2tl64cvfz67dugx4df0t93y96fnqx4uq7e8qvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTWkzS2tWcklCV3dDMGI2
            SzFhanNPczkrTENvZHpFeCs1NG1ZeWFZekJvCjNuU3F2YmY1NmRpVWROYmh5cTlI
            K21mM2FxVCtuemo4UllHVUJWOTk1MVUKLS0tIGFva1JlTTF5VFZvZjdWb21XSENz
            UllWY1lCZ1lpRERqRHlGUjJ6bGMvd2cK18t3KZQ2QoU2tkoK68fdddqisk0Z1MUb
            qBxgwJcHmkisRaB3b2pHGy212bBqdPApzQqnND6b3g3h3XO4nyG5EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T02:04:45Z"
    mac: ENC[AES256_GCM,data:sRaZ4B2CwYvcvQueVQk0Kieq3Rbtc6IEvttl9EaOInoskud2Jt4yh69x5jJTQWsaOVhnY0Lj4y7TqXEAOb+XwXryuHZtiSIqj0/rNt8ndfLsNRW6omKntT3E5SWtUD85iFCSH9MbUhweeMAk46hNEE+JwXdeOpfKkKEtUkhUcM8=,iv:FZAyoVQAvtkRlJvWBWVrXY1wvRr/7i0a3NeX6k2nKi0=,tag:UDLiYCha3IR5x/yiQtSC8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
